spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/memes
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

server:
  error:
    include-message: always
  port: 8080